apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: asdf-nodejs-gitops
  description: This is GitOps manifest for asdf-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=asdf-nodejs
    backstage.io/kubernetes-id: asdf-nodejs 
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: chetna14manku-org/asdf-nodejs-gitops
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: chetna14manku-org.asdf-nodejs-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:asdf-nodejs
